
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma config(Motor,  port2,           m2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           m3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           m4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           m5,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           m6,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           m7,            tmotorVex393_MC29, openLoop)

//#pragma config(Motor,  port1,           m1,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	    while(true) {
		        //Ch2 and Ch3 are joysticks
		        motor[port2] = -vexRT[Ch2]; //Full power is 127; 2nd joystick y axis (up and down)
		        motor[port3] = -vexRT[Ch2]; //for some reason motors 2 and 3 were going the opposite direction so I just reversed them
		        motor[port4] = vexRT[Ch3];
		        motor[port5] = vexRT[Ch3];

		     if(vexRT[Btn6U] == 1)//when the up trigger is pressed
			     {
			     motor[port6] = 40;
			     motor[port7] = 40;
			     }
		     else if(vexRT[Btn6D] == 1)//when the down trigger is pressed
			     {
			     motor[port6] = -40;
			     motor[port7] = -40;
			     }
		     else
			     {
			     motor[port6] = 0;
			     motor[port7] = 0;
			     }

		        wait1Msec(50);
		    }
}
